services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-novaminds
    environment:
      MYSQL_DATABASE: novamindsDB
      MYSQL_ROOT_PASSWORD: novaminds1234
    ports:
      - 3306:3306
    volumes:
      - novaminds-mysql-data:/var/lib/mysql
    networks:
      - novaminds-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10

  app:
    image: 600627338836.dkr.ecr.ap-northeast-2.amazonaws.com/just-fridge-server:latest
    container_name: novaminds-app
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod,oauth,jwt,s3,email
    networks:
      - novaminds-network

  nginx:
    image: nginx:alpine
    container_name: novaminds-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - app
    networks:
      - novaminds-network

networks:
  novaminds-network:
    driver: bridge

volumes:
  novaminds-mysql-data: