version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-novaminds
    environment:
      MYSQL_DATABASE: novamindsDB
      MYSQL_ROOT_PASSWORD: novaminds1234
    ports:
      - 3307:3306
    volumes:
      - novaminds-mysql-data:/var/lib/mysql
    networks:
      - novaminds-network

networks:
  novaminds-network:
    driver: bridge

volumes:
  novaminds-mysql-data: