services:
  # Spring Boot 애플리케이션
  app:
    image: 600627338836.dkr.ecr.ap-northeast-2.amazonaws.com/just-fridge-server:latest
    container_name: novaminds-app
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod,oauth,jwt,s3,email,redis
    restart: unless-stopped
    networks:
      - app-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      # nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # GitHub Actions에서 전송할 nginx 설정 파일들
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app

# Docker 네트워크
networks:
  app-network:
    driver: bridge