version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-novaminds
    environment:
      MYSQL_ROOT_PASSWORD: Dhyy03171!
      MYSQL_DATABASE: novamindsDB
      MYSQL_USER: novaminds
      MYSQL_PASSWORD: novaminds1234
    ports:
      - "3307:3306"
    volumes:
      - novaminds-mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  novaminds-mysql-data: