spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
        auto: false
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      stack:
        auto: false

cloud:
  aws:
    s3:
      bucket: grad-recipe