spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DATABASE}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ✅ 첫 배포시 update, 안정화 후 validate로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false

# ✅ 운영 환경 로깅 설정
logging:
  level:
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    novaminds.gradproj: INFO