spring:
  datasource:
    url: jdbc:mysql://${DOCKER_MYSQL_HOST}:${DOCKER_MYSQL_PORT}/${DOCKER_MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ${DOCKER_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  docker:
    compose:
      enabled: true
      file: compose-dev.yml
      lifecycle-management: start_and_stop